### ISSUE TITLE
Header footer mobile unfriendly

### ISSUE THREAD

**Issue by drdhaval2785** [ashtadhyayi/ui#1]
1. Search box overflows.
2. Footer falls short by some mm.
3. Red color at top and bottom is too eyecatching. Maybe we can keep it pinkish, which is used to highlight sutras in text.

**Comment by drdhaval2785** [comment]
![screenshot_20181221-074457_samsung internet](https://user-images.githubusercontent.com/5755132/50323003-b3208280-04fd-11e9-8869-1daf26c9b268.jpg)

**Comment by vvasuki** [comment]
शोधितम्।
