### ISSUE TITLE
frequency of regeneration of webpages

### ISSUE THREAD

**Issue by drdhaval2785** [ashtadhyayi/ui#3]
I could not find what is the frequency or timing of regenerating the new webpages by Hugo.
That would help us understand when our corrections will be visible in the frontend.

**Comment by vvasuki** [comment]
Pages will have to be manually regenerated and pushed by someone (with instructions in the about page). Doesn't happen automatically.

**Comment by drdhaval2785** [comment]
https://bwaycer.github.io/hugo_tutorial.hugo/tutorials/automated-deployments/ seems to be the way to automate.

**Comment by vvasuki** [comment]
Nice! After long learning + hacking hours, done - https://app.wercker.com/vvasuki/ui/runs . Invited @drdhaval2785 to manage on wercker.

**Comment by vvasuki** [comment]
Actually (not 100% sure) but this might only trigger updates when changes are made to the master branch of this repo and not on changes to https://github.com/sanskrit/ashtadhyayi/issues .

**Comment by vvasuki** [comment]
Added a new pipeline https://app.wercker.com/vvasuki/ashtadhyayi/ to trigger the ui. So, we're set. 

Not sure how the pricing works though!

**Comment by vvasuki** [comment]
Can you check again?

Both of the following wercker jobs should finish:
-  https://app.wercker.com/vvasuki/ashtadhyayi/runs
-  https://app.wercker.com/vvasuki/ui/runs

for you to see the changes. And they seem to have run and lead to a commit ~ 1 hour ago - https://github.com/ashtadhyayi/ui/commits/gh-pages .

**Comment by drdhaval2785** [comment]
There is no change in https://ashtadhyayi.github.io/ui/?sutra=1.2.5 from the previous version. It should have changed formatting and pink color because of the commit https://github.com/sanskrit/ashtadhyayi/commit/7e8de429fc4d209cfc3b6af11c9c54b918bf360f

**Comment by vvasuki** [comment]
Ah I see that the "update submodules" step is failing:
```
Submodule path 'content/vritti': checked out '6730d767adcd0606e0f2be604afa605176701bad'
Submodule path 'themes/ananke': checked out '04a27b7ed9aed228c35561b4ba0cfc7fe79951c1'
```

**Comment by vvasuki** [comment]
समीकृतमधुनेति परीक्षया ज्ञायते।

**Comment by drdhaval2785** [comment]
Works.
