### ISSUE TITLE
Two edit buttons in the same page

### ISSUE THREAD

**Issue by drdhaval2785** [ashtadhyayi/ui#4]
In individual commentary UI

**Comment by drdhaval2785** [comment]
![screenshot_20181222-081504_chrome](https://user-images.githubusercontent.com/5755132/50369856-d7459780-05c1-11e9-9d0d-739f2088413c.jpg)

**Comment by drdhaval2785** [comment]
I would request for removal of header kne.

**Comment by vvasuki** [comment]
I deliberately put two buttons - just to make sure that people find the edit button without trouble. The multiplicity does not make the user confused in any way - भवच्चिन्तनं किम्?

**Comment by vvasuki** [comment]
अन्ततो गत्वा पृष्ठेषु समता ऽस्त्विति उर्ध्ववर्तिकीलकं निष्कासितम्।
