### ISSUE TITLE
hyperlinking sutra numbers

### ISSUE THREAD

**Issue by chandrasekharanr** [ashtadhyayi/ui#5]
Right now, the UI does not have the sutra numbers hyperlinked.

**Comment by vvasuki** [comment]
Hyperlinks added.

**Comment by vvasuki** [comment]
काश्चनसूत्रसङ्ख्या देवनागर्या सन्ति। ते खलु https://github.com/sanskrit/ashtadhyayi इत्यत्रैव परिवर्तनीयाः (अन्यटीकाभिस् सह समत्वाय)।

**Comment by vvasuki** [comment]
अधुना देवनागरीसुत्राङ्कनान्यपि प्रेक्षकं पृष्ठान्तरं नेतुं‌ क्षमानि।
